### ISSUE TITLE
Unknown argument in config file: inference_batchsize

### ISSUE THREAD

**Issue by Takashibobbob** [torchmd/torchmd-protein-thermodynamics#14]
Hello, 
I start to use coordinates and delta-forces to train the network. However, when I typed the command "CUDA_VISIBLE_DEVICES=0 python /users/ssyjb1/torchmd-net/torchmdnet/scripts/train.py --conf train.yaml --log-dir train_light" it shows the error below. Can you help me solve this issue?

```
(torchmd-net) [ssyjb1@popeye data]$ CUDA_VISIBLE_DEVICES=0 python /users/ssyjb1/torchmd-net/torchmdnet/scripts/train.py --conf train.yaml --log-dir train_light
/users/ssyjb1/anaconda3/envs/torchmd/envs/torchmd-net/lib/python3.11/site-packages/torch_geometric/typing.py:18: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: /users/ssyjb1/anaconda3/envs/torchmd/envs/torchmd-net/lib/python3.11/site-packages/libpyg.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
/users/ssyjb1/anaconda3/envs/torchmd/envs/torchmd-net/lib/python3.11/site-packages/torch_geometric/typing.py:42: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /users/ssyjb1/anaconda3/envs/torchmd/envs/torchmd-net/lib/python3.11/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "/users/ssyjb1/torchmd-net/torchmdnet/scripts/train.py", line 206, in <module>
    main()
  File "/users/ssyjb1/torchmd-net/torchmdnet/scripts/train.py", line 127, in main
    args = get_args()
           ^^^^^^^^^^
  File "/users/ssyjb1/torchmd-net/torchmdnet/scripts/train.py", line 109, in get_args
    args = parser.parse_args()
           ^^^^^^^^^^^^^^^^^^^
  File "/users/ssyjb1/anaconda3/envs/torchmd/envs/torchmd-net/lib/python3.11/argparse.py", line 1869, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/ssyjb1/anaconda3/envs/torchmd/envs/torchmd-net/lib/python3.11/argparse.py", line 1902, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/ssyjb1/anaconda3/envs/torchmd/envs/torchmd-net/lib/python3.11/argparse.py", line 2114, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/ssyjb1/anaconda3/envs/torchmd/envs/torchmd-net/lib/python3.11/argparse.py", line 2054, in consume_optional
    take_action(action, args, option_string)
  File "/users/ssyjb1/anaconda3/envs/torchmd/envs/torchmd-net/lib/python3.11/argparse.py", line 1978, in take_action
    action(self, namespace, argument_values, option_string)
  File "/users/ssyjb1/torchmd-net/torchmdnet/utils.py", line 150, in __call__
    raise ValueError(f"Unknown argument in config file: {key}")
ValueError: Unknown argument in config file: inference_batchsize
```

**Comment by LuZhuanz** [comment]
same question

**Comment by giadefa** [comment]
ValueError: Unknown argument in config file: inference_batchsize


The new versions of TorchMD-net removed this. Either use an older version
or try to adapt it.
